### PR TITLE
Fix cherry-pick aborting

### PR DESCRIPTION
**Pull request by jack1142**
While I can't really confirm whether this has been an issue for miss-islington since I'm not running it myself (I am however working on a bot for a different project, which also uses `CherryPicker` API and I have ran in these kinds of issues), I believe this should fix some issues related to backport task trying to abort the cherry-pick when the backport fails.

If I haven't missed something, before this change `abort_cherry_pick()` would fail to run due to CherryPicker's `initial_state` not being `BACKPORT_PAUSED`. `initial_state` is, as the name suggests, initial and therefore it doesn't get updated when a new state is set.

This means that when `CherryPickException` is raised, the `initial_state` still is set to `UNSET` rather than `BACKPORT_PAUSED` therefore not allowing to abort. To solve this, I make *another* instance of `CherryPicker` after this exception is raised.

As for `BranchCheckoutException`, currently when this is raised, the state that cherry-picker ends up with is `BACKPORT_LOOP_START` which is why instead of making another instance of `CherryPicker` (which would lead to an error due to it being an unallowed state; note: this can also be an issue when running cherry-picker from CLI), I resorted to a bit more hacky solution of just changing its state to a valid one. I know it would be better to solve this in `cherry-picker` itself in some way but I wasn't exactly sure how the maintainers of it would want to proceed about it. See https://github.com/python/cherry-picker/issues/38

### CODE REVIEW

**Comment by jack1142** [comment]
> While I can't really confirm whether this has been an issue for miss-islington since I'm not running it myself

After digging a bit more, I found that this has definitely been an issue for miss-islington [back in 2019](https://github.com/python/core-workflow/issues/257#issuecomment-508065535) so it most likely still is a problem based on what has happened in miss-islington's git history since July 2019.

**Comment by jack1142** [comment]
It's very possible that the PR I made on the cherry-picker repo (https://github.com/python/cherry-picker/pull/39) is enough to solve this and this PR is unnecessary but I failed to mention whether it's enough when I wrote it (damn you, past me 😄) and I can't actually say it fixes it for sure.

I might try figuring that out later this week but no guarantees there.

**Comment by Mariatta** [comment]
I think let's start by fixing the cherry-picker CLI first and see if the problem still persists.

**Comment by Mariatta** [comment]
Closing the PR. I plan to release cherry-picker later this week. Thanks!

**Pull request closed without merging**
