### PR TITLE
Don't immediately delete PR's branch in case it's close&reopen

### LINKED ISSUE #70: Odd backport failure
When I merged https://github.com/python/cpython/pull/5981 with backport labels, the usual backport PRs were generated and I approved both.  https://github.com/python/cpython/pull/5986 for 3.7 went normally.  https://github.com/python/cpython/pull/5987 for 3.6 got hung-up waiting for Appveyor to report.  I could not check details because there was no details link.  Miss I. twice said "Backport status check is done, and it's a success", which usually triggers a merge.   To try to restart CI, I closed and opened, but Miss I. reclosed, permanently.

I went back to original PR and re-added 3.6 backport label.  https://github.com/python/cpython/pull/5993 then proceeded normally.

I don't know that there is anything to do, except to take notice of a new? failure mode.

### PR DESCRIPTION
**Pull request by jack1142**
Fixes #70 

Alternatively, we could create a task and add a listener for `reopen` that will cancel the existing task if one exists.

### CODE REVIEW

**Comment by jack1142** [comment]
After a second thought, perhaps the sleep should be lower? Like 15 seconds?

**Comment by jack1142** [comment]
I have to update tests here.

**Comment by jack1142** [comment]
> I have to update tests here.

Done.

**Review by Mariatta — APPROVED** [review]
I think this is a great solution.
Thank you!

**Pull request merged**
