### PR TITLE
Use GH to signify Github handle of the user instead of "@".

### LINKED ISSUE #270: "Automerge-Triggered-By: @githubhandle" message causes spam
Since miss-islington uses a GitHub handle in the "Automerge-Triggered-By" 'header', whoever triggered the automerge gets spammed any time a contributor does something strange in their own fork of the repo that causes a new commit with the same "Automerge-Triggered-By" message to be pushed to their fork.  For example, I was just notified about [this commit](https://github.com/PatrikKopkan/cpython/commit/855cd8bdf99e156e9baee55dd45f6e39b671ed68) this morning.

I would prefer using display name (`Zachary Ware`, possibly with email address if public) rather than GitHub handle (`@zware`) for this message, which also makes it easier to tie the committer to the commit since the GitHub handle is not actually present anywhere else in the Git repository.

### LINKED ISSUE #272: Only mention author on backport PRs in case of errors
Initially done via https://github.com/python/miss-islington/pull/27 for https://github.com/python/miss-islington/issues/26.

https://github.com/python/miss-islington/issues/26 was asking for this to be done in case of errors, but it gets done always.

This caused like 4+ notifications due to a PR being backported to 3.7 and 3.8.

Ref: https://github.com/python/cpython/pull/16066#issuecomment-530902229

### PR DESCRIPTION
**Pull request by maxking**
"@" usually doesn't give any information about what exactly the handle means
since we don't know it is a Github handle from the commit message.

Changing the pattern to be `GH:` similar to what we do for Pull Requests
with (GH-).

Fixes #270

### CODE REVIEW

**Comment by maxking** [comment]
ping @Mariatta 

Any thoughts on this?

**Comment by merwok** [comment]
This would really improve quality of (github) life! :rocket:

**Comment by merwok** [comment]
Rebase happening in #405

**Comment by Mariatta** [comment]
We're using the change in #405 instead of this one. Thanks.

**Pull request closed without merging**
